/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ravc.leitorxml.views;

import br.com.swconsultoria.nfe.schema_4.enviNFe.TIpi;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe.InfNFe.Det;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TNfeProc;
import com.ravc.leitorxml.utils.CellRenderer;
import com.ravc.leitorxml.utils.Tools;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBElement;

/**
 *
 * @author Rodrigo
 */
public class LeitorXML extends javax.swing.JFrame {

    private static final Point point = new Point();
    /**
     * Creates new form LeitorXML
     */
    public LeitorXML() {
        initComponents();
        setIconImage(Tools.getImage("icons8_view_details_50px.png"));
        
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        jTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable.setDefaultEditor(Object.class, null);
        jTable.setDefaultRenderer(Object.class, new CellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlStatus = new javax.swing.JLabel();
        jbSelectFolder = new javax.swing.JButton();
        jpProgress = new javax.swing.JProgressBar();
        jbListFiles = new javax.swing.JButton();
        jtfSearchPath = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfVlrProdutos = new javax.swing.JTextField();
        jtfVlrTotal = new javax.swing.JTextField();
        jtfVlrAcrescimos = new javax.swing.JTextField();
        jtfVlrDescontos = new javax.swing.JTextField();
        jtfVlrBaseIPI = new javax.swing.JTextField();
        jtfVlrIPI = new javax.swing.JTextField();
        jtfVlrBaseICMSST = new javax.swing.JTextField();
        jtfVlrICMSST = new javax.swing.JTextField();
        jtfVlrBaseICMS = new javax.swing.JTextField();
        jtfVlrICMS = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jcbCalcProductsDesc = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leitor de XMLs");
        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(25, 49, 73));
        jPanel4.setPreferredSize(new java.awt.Dimension(1100, 15));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 94));

        jlStatus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlStatus.setForeground(new java.awt.Color(198, 255, 0));
        jlStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jbSelectFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_folder_20px.png"))); // NOI18N
        jbSelectFolder.setToolTipText("Selecionar pasta");
        jbSelectFolder.setBorder(null);
        jbSelectFolder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSelectFolder.setFocusPainted(false);
        jbSelectFolder.setFocusable(false);
        jbSelectFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectFolderActionPerformed(evt);
            }
        });

        jpProgress.setBackground(new java.awt.Color(40, 65, 91));
        jpProgress.setForeground(new java.awt.Color(198, 255, 0));
        jpProgress.setPreferredSize(new java.awt.Dimension(146, 8));
        jpProgress.setString("");
        jpProgress.setStringPainted(true);

        jbListFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_list_20px.png"))); // NOI18N
        jbListFiles.setToolTipText("Listar documentos");
        jbListFiles.setBorder(null);
        jbListFiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbListFiles.setFocusPainted(false);
        jbListFiles.setFocusable(false);
        jbListFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListFilesActionPerformed(evt);
            }
        });

        jtfSearchPath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfSearchPathFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Caminho da pasta com os XMLs:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfSearchPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSelectFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jbListFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 1011, Short.MAX_VALUE))
                    .addComponent(jpProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSearchPath, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelectFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbListFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 7, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        jTable.setBackground(new java.awt.Color(240, 240, 240));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Série/Numero", "CNPJ/CPF", "Razão Social/Nome", "Situação", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setColumnSelectionAllowed(true);
        jTable.setDropMode(javax.swing.DropMode.ON);
        jTable.setGridColor(new java.awt.Color(25, 49, 73));
        jTable.setOpaque(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMinWidth(100);
            jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable.getColumnModel().getColumn(1).setMinWidth(130);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(130);
            jTable.getColumnModel().getColumn(1).setMaxWidth(130);
            jTable.getColumnModel().getColumn(2).setMinWidth(150);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable.getColumnModel().getColumn(3).setMinWidth(100);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable.getColumnModel().getColumn(4).setMinWidth(100);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable.getColumnModel().getColumn(5).setMinWidth(100);
            jTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(995, 120));

        jLabel2.setText("Valor Total:");

        jLabel3.setText("Total Produtos:");

        jLabel4.setText("Descontos:");

        jLabel5.setText("Base ICMS:");

        jLabel6.setText("Valor ICMS:");

        jLabel7.setText("Base ICMS ST:");

        jLabel8.setText("Valor ICMS ST:");

        jLabel9.setText("Base IPI:");

        jLabel10.setText("Valor IPI:");

        jLabel11.setText("Acréscimos:");

        jtfVlrProdutos.setEditable(false);
        jtfVlrProdutos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrProdutos.setFocusable(false);

        jtfVlrTotal.setEditable(false);
        jtfVlrTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrTotal.setFocusable(false);

        jtfVlrAcrescimos.setEditable(false);
        jtfVlrAcrescimos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrAcrescimos.setFocusable(false);

        jtfVlrDescontos.setEditable(false);
        jtfVlrDescontos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrDescontos.setFocusable(false);

        jtfVlrBaseIPI.setEditable(false);
        jtfVlrBaseIPI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrBaseIPI.setFocusable(false);

        jtfVlrIPI.setEditable(false);
        jtfVlrIPI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrIPI.setFocusable(false);

        jtfVlrBaseICMSST.setEditable(false);
        jtfVlrBaseICMSST.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrBaseICMSST.setFocusable(false);

        jtfVlrICMSST.setEditable(false);
        jtfVlrICMSST.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrICMSST.setFocusable(false);

        jtfVlrBaseICMS.setEditable(false);
        jtfVlrBaseICMS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrBaseICMS.setFocusable(false);

        jtfVlrICMS.setEditable(false);
        jtfVlrICMS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVlrICMS.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVlrBaseICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVlrBaseICMSST, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrICMSST, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVlrBaseIPI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrIPI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVlrDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfVlrProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jtfVlrBaseICMSST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfVlrICMSST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jtfVlrBaseICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfVlrICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfVlrBaseIPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfVlrIPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jtfVlrDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfVlrAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfVlrProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Principal", jPanel5);

        jcbCalcProductsDesc.setText("Considerar produtos nos totais de descontos");
        jcbCalcProductsDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbCalcProductsDesc.setFocusPainted(false);
        jcbCalcProductsDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_20px_grayscale.png"))); // NOI18N
        jcbCalcProductsDesc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbCalcProductsDesc)
                .addContainerGap(952, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbCalcProductsDesc)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opções", jPanel6);

        jPanel3.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbListFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListFilesActionPerformed
        loadTable();
    }//GEN-LAST:event_jbListFilesActionPerformed

    private void jbSelectFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectFolderActionPerformed
        JFileChooser fc = new JFileChooser();

        File currentDirectory = new File(System.getProperty("user.dir"));
        fc.setCurrentDirectory(currentDirectory);

        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File directory = fc.getSelectedFile();
            jtfSearchPath.setText(directory.getPath());
        }
    }//GEN-LAST:event_jbSelectFolderActionPerformed

    private void jtfSearchPathFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSearchPathFocusGained
        if (evt.getSource() instanceof JFormattedTextField) {
            final JFormattedTextField jftf
                    = (JFormattedTextField) evt.getSource();
            SwingUtilities.invokeLater(() -> {
                jftf.selectAll();
            });
        } else if (evt.getSource() instanceof JTextField) {
            JTextField jtf = (JTextField) evt.getSource();
            jtf.selectAll();
        }
    }//GEN-LAST:event_jtfSearchPathFocusGained

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeitorXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeitorXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeitorXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeitorXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeitorXML().setVisible(true);
//            }
//        });
//    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbListFiles;
    private javax.swing.JButton jbSelectFolder;
    private javax.swing.JCheckBox jcbCalcProductsDesc;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JProgressBar jpProgress;
    private javax.swing.JTextField jtfSearchPath;
    private javax.swing.JTextField jtfVlrAcrescimos;
    private javax.swing.JTextField jtfVlrBaseICMS;
    private javax.swing.JTextField jtfVlrBaseICMSST;
    private javax.swing.JTextField jtfVlrBaseIPI;
    private javax.swing.JTextField jtfVlrDescontos;
    private javax.swing.JTextField jtfVlrICMS;
    private javax.swing.JTextField jtfVlrICMSST;
    private javax.swing.JTextField jtfVlrIPI;
    private javax.swing.JTextField jtfVlrProdutos;
    private javax.swing.JTextField jtfVlrTotal;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        new Thread(() -> {
            try {
                System.out.println("Iniciando listagem de arquivos, aguarde...");
                System.out.println("");
                jlStatus.setText("Iniciando listagem de arquivos, aguarde...");
                if (jtfSearchPath.getSelectedText() != null
                        && !jtfSearchPath.getSelectedText().trim().equals("")) {

                    DefaultTableModel table = (DefaultTableModel) jTable.getModel();
                    table.setRowCount(0);

                    List<File> files = Files.list(Paths.get(jtfSearchPath.getSelectedText()))
                            .map(Path::toFile)
                            .filter(f -> f.getPath().endsWith(".xml"))
                            .collect(Collectors.toList());
                    int progress = 0;
                    int totalProgress = files.size();
                    jpProgress.setMaximum(files.size());
                    jlStatus.setText("Verificando " + progress + " de "
                            + totalProgress + ", aguarde...");

                    double vlrProdutos = 0.00;
                    double vlrTotal = 0.00;

                    double vlrDescontos = 0.00;
                    double vlrAcrescimos = 0.00;

                    double vlrBaseICMS = 0.00;
                    double vlrICMS = 0.00;
                    double vlrBaseICMSST = 0.00;
                    double vlrICMSST = 0.00;
                    double vlrBaseIPI = 0.00;
                    double vlrIPI = 0.00;

                    for (File file : files) {
                        System.out.println("-----------------------------------------------------");
                        System.out.println("Arquivo encontrado: " + file.getPath());
                        TNfeProc nfe = Tools.readXML(file.getPath());
                        System.out.println("Validação: "
                                + nfe.getNFe() != null
                                ? "Arquivo valido (NFe)" : "Arquivo inválido");
                        if (nfe != null
                                && nfe.getNFe() != null) {
                            table.addRow(new Object[]{
                                Tools.asDateZonedDateTime(nfe.getNFe().getInfNFe()
                                .getIde().getDhEmi()),
                                nfe.getNFe().getInfNFe().getIde().getSerie()
                                + " / " + nfe.getNFe().getInfNFe().getIde().getNNF(),
                                nfe.getNFe().getInfNFe().getEmit().getCPF() == null
                                ? nfe.getNFe().getInfNFe().getEmit().getCNPJ()
                                : nfe.getNFe().getInfNFe().getEmit().getCPF(),
                                nfe.getNFe().getInfNFe().getEmit().getXNome(),
                                nfe.getNFe().getSignature() != null ? "Aprovada" : "Não aprovada",
                                Tools.currency(Double.valueOf(nfe.getNFe().getInfNFe()
                                .getTotal().getICMSTot().getVNF()))
                            });

                            for (Det produto : nfe.getNFe().getInfNFe().getDet()) {

                                for (JAXBElement<?> e : produto.getImposto().getContent()) {
                                    if (e.getValue() instanceof TIpi) {
                                        TIpi ipi = (TIpi) e.getValue();

                                        if (ipi.getIPITrib() != null) {
                                            vlrBaseIPI = vlrBaseIPI
                                                    + Tools.currency(ipi.getIPITrib()
                                                            .getVBC());
                                            vlrIPI = vlrIPI
                                                    + Tools.currency(ipi.getIPITrib()
                                                            .getVIPI());
                                        }
                                    }
                                }
                                if (jcbCalcProductsDesc.isSelected()
                                        && produto.getProd().getVDesc() != null) {
                                    vlrDescontos = vlrDescontos
                                            + Double.valueOf(produto.getProd()
                                                    .getVDesc());
                                }
                            }

                            if (!jcbCalcProductsDesc.isSelected()) {
                                vlrDescontos = vlrDescontos
                                        + Double.valueOf(nfe.getNFe().getInfNFe()
                                                .getTotal().getICMSTot().getVDesc());
                            }

                            vlrProdutos = vlrProdutos
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVProd());
                            vlrTotal = vlrTotal
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVNF());

                            vlrAcrescimos = vlrAcrescimos
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVOutro());

                            vlrBaseICMS = vlrBaseICMS
                                    + Double.valueOf(nfe.getNFe().getInfNFe().
                                            getTotal().getICMSTot().getVBC());
                            vlrICMS = vlrICMS
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVICMS());

                            vlrBaseICMSST = vlrBaseICMSST
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVBCST());
                            vlrICMSST = vlrICMSST
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVST());

                            vlrIPI = vlrIPI
                                    + Double.valueOf(nfe.getNFe().getInfNFe()
                                            .getTotal().getICMSTot().getVIPI());
                        }

                        jlStatus.setText("Verificando " + progress + " de "
                                + totalProgress + ", aguarde...");
                        progress++;
                        jpProgress.setValue(progress);
                    }

                    jtfVlrProdutos.setText(Tools.currency(vlrProdutos));
                    jtfVlrTotal.setText(Tools.currency(vlrTotal));

                    jtfVlrDescontos.setText(Tools.currency(vlrDescontos));
                    jtfVlrAcrescimos.setText(Tools.currency(vlrAcrescimos));

                    jtfVlrBaseICMS.setText(Tools.currency(vlrBaseICMS));
                    jtfVlrICMS.setText(Tools.currency(vlrICMS));
                    jtfVlrBaseICMSST.setText(Tools.currency(vlrBaseICMSST));
                    jtfVlrICMSST.setText(Tools.currency(vlrICMSST));
                    jtfVlrBaseIPI.setText(Tools.currency(vlrBaseIPI));
                    jtfVlrIPI.setText(Tools.currency(vlrIPI));
                    System.out.println("### Processo finalizado com sucesso! ###");
                    jlStatus.setText("Processo finalizado com sucesso!");
                }
            } catch (Exception e) {
                System.out.println("Problemas encontrados!");
                System.out.println("Localização: " + e.getLocalizedMessage());
                System.out.println("Mensagem: \n" + e.getMessage());
                JOptionPane.showMessageDialog(this,
                        "Problemas encontrados ao realizar listagem, motivo:\n"
                        + e.getMessage());
//                e.printStackTrace();
            }
        }).start();
    }
}
